update
Yosef-Adler/Button_show pull request #1
Opened 2023-07-27 11:24 UTC by Yosef-Adler

2023-07-27 12:12 UTC, reuven-yanturin requested changes

2023-07-27 12:12 UTC, reuven-yanturin commented on button.html
> +    <h1>hello world</h1>
вот так выглядит комент на твои изменения)

2023-07-27 12:15 UTC, Yosef-Adler commented on button.html
> +    <h1>hello world</h1>
т.е. нужно вносить коммент в саму измененную строку?) 
ок

2023-07-27 12:25 UTC, reuven-yanturin commented on button.html
> +    <h1>hello world</h1>
нет, я имею в виду если я в коде увижу то что нужно поменять или удалить, то можно добавить комент прям на эту строчку)

2023-07-27 12:25 UTC, reuven-yanturin requested changes

2023-07-27 12:25 UTC, reuven-yanturin commented on button.html
> +    <h1>hello world</h1>
```suggestion
    <h1>shalom world</h1>
```

2023-07-27 12:26 UTC, reuven-yanturin commented on button.html
> +    <h1>hello world</h1>
так же можно еще предложить внести свои изменения

2023-07-30 08:49 UTC, Yosef-Adler commented on button.html
> +    <h1>hello world</h1>
got it

2023-07-30 14:40 UTC, closed without merging

2023-07-30 14:40 UTC, Yosef-Adler commented
out of date